spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  config:
    import: configserver:http://${toucan.config.server.ip}:${toucan.config.server.port}
  cloud:
    config:
      username: toucan_sp
      password: toucan_sp_0987
      label: master
    nacos:
      discovery:
        server-addr: ${toucan.nacos.ip}:${toucan.nacos.port}
        fail-fast: false
        username: ${toucan.nacos.username}
        password: ${toucan.nacos.password}
    loadbalancer:
      nacos:
        enabled: true
  application:
    name: toucan-shopping-gateway

logging:
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      profile: prod

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      profile: dev
