
server:
  port: 8089


#eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 3 #3秒没有心跳就剔除
#    lease-renewal-interval-in-seconds: 3 #心跳3秒
#    prefer-ip-address: true
#    instance-id: 127.0.0.1:8089    #使用IP地址注册
#  client:
#    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka


#开启饥饿加载
ribbon:
  ServerListRefreshInterval: 3000 #3秒钟更新一次服务列表缓存
  eager-load:
    enabled: true
    clients: "toucan-shopping-order,\
              toucan-shopping-product,\
              toucan-shopping-admin-auth,\
              toucan-shopping-column,\
              toucan-shopping-common-data,\
              toucan-shopping-content,\
              toucan-shopping-user,\
              toucan-shopping-seller,\
              toucan-shopping-message,\
              toucan-shopping-stock"



spring:
  application:
    name: toucan-shopping-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
  cloud:
    nacos:
      discovery:
        ip: ${toucan.ip}    #使用IP地址注册
        port: ${server.port}
        server-addr: http://${toucan.nacos.ip}:${toucan.nacos.port}
        metadata:
          preserved.heart.beat.interval: 2000 #心跳间隔。时间单位:秒。心跳间隔
          preserved.heart.beat.timeout: 2500 #心跳暂停。时间单位:秒。 即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.ip.delete.timeout: 2500 #Ip删除超时。时间单位:秒。即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例删除：
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: toucan-shopping-product-proxy
          uri: lb://toucan-shopping-product
          predicates:
            - Path=/toucan-shopping-product-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-order-proxy
          uri: lb://toucan-shopping-order
          predicates:
            - Path=/toucan-shopping-order-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-user-proxy
          uri: lb://toucan-shopping-user
          predicates:
            - Path=/toucan-shopping-user-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-common-data-proxy
          uri: lb://toucan-shopping-common-data
          predicates:
            - Path=/toucan-shopping-common-data-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-stock-proxy
          uri: lb://toucan-shopping-stock
          predicates:
            - Path=/toucan-shopping-stock-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-content-proxy
          uri: lb://toucan-shopping-content
          predicates:
            - Path=/toucan-shopping-content-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-message-proxy
          uri: lb://toucan-shopping-message
          predicates:
            - Path=/toucan-shopping-message-proxy/**
          filters:
            - StripPrefix=1
        - id: toucan-shopping-admin-auth-proxy
          uri: lb://toucan-shopping-admin-auth
          predicates:
            - Path=/toucan-shopping-admin-auth-proxy/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@pathKeyResolver}'
                redis-rate-limiter.replenishRate: 900  #令牌桶每秒填充平均速率,QPS 900
                redis-rate-limiter.burstCapacity: 1000 #令牌桶总容量
        - id: toucan-shopping-seller-proxy
          uri: lb://toucan-shopping-seller
          predicates:
            - Path=/toucan-shopping-seller-proxy/**
          filters:
            - StripPrefix=1


