#========================权限中台界面 生产环境====================================

server:
  port: 8098
  servlet:
    context-path: /
spring:
  application:
    name: toucan-shopping-admin-auth-web #应用名称
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  task:
    execution:
      pool:
        core-size: 5 #核心线程
        max-size: 10 #最大线程
        queue-capacity: 150 #缓冲队列
        keep-alive: 20s #允许空闲时间(秒)
        name-prefix: async-thread-pool
  zipkin: #链路追踪
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  compression: #开启gzip压缩
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 #只压缩1MB以上的内容
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        enabled: false

#eureka:
#  client:
#    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://${toucan.eureka.ip}:${toucan.eureka.port}/eureka



toucan:
  machine-id: 2201 #机器编码
  app-code: 10001003 #自定义应用编码
  #雪花算法ID相关
  # workerId: 0 #工作ID 0~31, 每个服务实例都有一个工作ID
  # datacenterId: 0 #数据中心ID (0~31)
  admin-auth:
    enabled: true
    operate-log: #操作日志
      enabled: true
      #记录指定路径
      path-patterns: /**
      #忽略记录
      exclude-path-patterns: /**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.gif,/**/*.json
    name: toucan-shopping-admin-auth
    #HTTP权限请求头
    # 例如 后台管理端 Cookie:10001003_aid=d10590b318544049ba2104d1f5517a7d;10001003_lt=d10590b318544049ba2104d1f5517a7d
    http-toucan-auth-header: Cookie
    #当前项目登录页
    login-page: login/page
    #没有权限时跳转页面
    page-403: /403
    #拦截指定路径
    path-patterns: /**
    #忽略拦截
    exclude-path-patterns: /**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.gif,/**/*.json,/403,/login/page,/login/vcode
  plugins:
    xss-filter:
      enabled: true
      #排除路径,多个用,分割(不支持正则,只有绝对路径,例如/user/login/password/form,/login/password)
      exclude-paths[0]: /function/update
      exclude-paths[1]: /function/save
  modules:
    adminAuthCache:
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    log: #日志模块
      param:
        #只配置请求即可,忽略以上请求日志
        ignore-url-patterns[0]: .*\.js
        ignore-url-patterns[1]: .*\.css
        ignore-url-patterns[2]: .*\.jpg
        ignore-url-patterns[3]: .*\.png
        ignore-url-patterns[4]: .*\.gif
        ignore-url-patterns[5]: .*\.json
        request:
          enabled: true
          content-type-list[0]: application/x-www-form-urlencoded
          content-type-list[1]: application/json
        response:
          enabled: true
          content-type-list[0]: application/json
      email:
        enabled: true
        title: ——权限中台应用——异常邮件
        ignore-exception-list[0]: javax.mail.MessagingException
        ignore-exception-list[1]: com.toucan.shopping.modules.common.exception.InvalidAdminHeaderException
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian

management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
