#========================用户中心服务 开发环境====================================

server:
  port: 8087
spring:
  application:
    name: toucan-shopping-user #应用名称
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
eureka:
  instance:
    lease-expiration-duration-in-seconds: 3 #3秒没发心跳将剔除
    lease-renewal-interval-in-seconds: 1 #心跳1秒
    prefer-ip-address: true
    instance-id: 127.0.0.1:8087    #使用IP地址注册
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    serviceUrl:
      defaultZone: http://localhost:8081/eureka





toucan:
  user:
    default-head-sculpture: group1/M00/00/00/rB5PVWC0wtCAfEp6AAAMz-h0lpc563_big.jpg
    default-personalized-signature: 这个人什么都没有写。
  machine-id: 2201 #机器编码
  app-code: 10001002 #用户中心 应用编码
  #雪花算法ID相关
  workerId: 0 #工作ID 0~31, 每个服务实例都有一个工作ID
  datacenterId: 0 #数据中心ID (0~31)
  sign:
    enabled: true
    sign-header: toucan-sign-header
    #拦截指定路径
    path-patterns: /**
  plugins:
    xss-filter:
      enabled: true
      exclude-paths:  #排除路径,多个用,分割(不支持正则,只有绝对路径,例如/user/login/password/form,/login/password)
  modules:
    userLoginCache:
      cache-type: redis
      redis-type: default  #实现方式类型 default 默认采用官方配置 customSharding 自定义分片
      default-redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
      custom-sharding-redis:
        login-cache-redis-list[0]:
          index: 0 #通过用户ID取余得到索引位置
          dbCount: 16 #这个节点的db数量
          select: single # 可选值 single:单实例 cluster:集群
          timeout: 10000
          password: mj_tocan_redis_7612 #多个集群要求每个密码统一
          #单实例
          host: 8.140.187.184
          port: 6379
          maxRedirects: 3 #最大连接转移数
          #jedis pool配置
          maxActive: 50 #最大活跃数
          maxWaitMillis: 15 #最大等待数
          maxIdle: 50 #最大核心线程数
          minIdle: 0 #最小核心线程数
#        login-cache-redis-list[1]:
#          index: 1 #通过用户ID取余得到索引位置
#          dbCount: 16 #这个节点的db数量
#          select: single # 可选值 single:单实例 cluster:集群
#          timeout: 10000
#          password:  #多个集群要求每个密码统一
#          #单实例
#          host: 8.140.187.184
#          port: 6379
#          maxRedirects: 3 #最大连接转移数
#          #jedis pool配置
#          maxActive: 50 #最大活跃数
#          maxWaitMillis: 15 #最大等待数
#          maxIdle: 50 #最大核心线程数
#          minIdle: 0 #最小核心线程数
    log: #日志模块
      email:
        enabled: false
        title: ——用户服务——异常邮件
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian
    toucanRedis: #redis模块
      select: single # 可选值 single:单实例 cluster:集群
      timeout: 10000
      password: mj_tocan_redis_7612 #多个集群要求每个密码统一
      #单实例
      host: 127.0.0.1
      port: 6379
      database: 0
      #集群配置
      hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
      maxRedirects: 3 #最大连接转移数
      #jedis pool配置
      maxActive: 50 #最大活跃数
      maxWaitMillis: 15 #最大等待数
      maxIdle: 50 #最大核心线程数
      minIdle: 0 #最小核心线程数
    skylarkLock: #云雀分布式锁
      type: redis #中间件类型
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 127.0.0.1
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
