#========================权限中台 生产环境====================================

server:
  port: ${toucan.port}
spring:
  application:
    name: toucan-shopping-admin-auth #应用名称
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
eureka:
  instance:
    lease-expiration-duration-in-seconds: 3 #3秒没发心跳将剔除
    lease-renewal-interval-in-seconds: 1 #心跳1秒
    prefer-ip-address: true
    instance-id: ${toucan.ip}:${toucan.port}    #使用IP地址注册
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    serviceUrl:
      defaultZone: http://${toucan.eureka.ip}:${toucan.eureka.port}/eureka




toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #商城应用编码
  #雪花算法ID相关
  workerId: 1 #工作ID 0~31, 每个服务实例都有一个工作ID
  datacenterId: 0 #数据中心ID (0~31)
  plugins:
    xss-filter:
      enabled: true
      exclude-paths: /function/update,/function/save  #排除路径,多个用,分割(不支持正则,只有绝对路径,例如/user/login/password/form,/login/password)
  modules:
    log: #日志模块
      email:
        enabled: true
        title: ——权限中台服务——异常邮件
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian