#========================权限中台 开发环境====================================

server:
  port: 8099
spring:
  application:
    name: toucan-shopping-admin-auth #应用名称
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
  task:
    execution:
      pool:
        core-threads: 5 #核心线程
        max-threads: 10 #最大线程
        queue-capacity: 150 #缓冲队列
        keep-alive: 20 #允许空闲时间(秒)
        name-prefix: async-thread-pool
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒没发心跳将剔除
    lease-renewal-interval-in-seconds: 3 #心跳3秒
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}    #使用IP地址注册
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    serviceUrl:
      defaultZone: http://localhost:8081/eureka




toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #商城应用编码
  #雪花算法ID相关
  workerId: 1 #工作ID 0~31, 每个服务实例都有一个工作ID
  datacenterId: 0 #数据中心ID (0~31)
  plugins:
    xss-filter:
      enabled: true
      exclude-paths: /function/update,/function/save  #排除路径,多个用,分割(不支持正则,只有绝对路径,例如/user/login/password/form,/login/password)
  modules:
    adminAuthCache:
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    log: #日志模块
      email:
        enabled: false
        title: ——权限中台服务——异常邮件
        ignore-exception-list[0]: javax.mail.MessagingException
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian