#========================秒杀服务 开发环境====================================

server:
  port: 8085
spring:
  application:
    name: toucan-shopping-second-kill #应用名称
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒没发心跳将剔除
    lease-renewal-interval-in-seconds: 3 #心跳3秒
    prefer-ip-address: true
    instance-id: 8.140.187.184:8085    #使用IP地址注册
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

feign:

  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 8
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

toucan:
  app-code: 10001001 #自定义应用编码
  admin-auth:
    enabled: false
    name: toucan-shopping-admin-auth
  modules:
    skylarkLock:
      type: redis
      redis:
        select: single
        timeout: 10000
        password: mj_tocan_redis_7612
        host: 8.140.187.184
        port: 6379
        database: 0
        maxActive: 50
        maxWaitMillis: 15
        maxIdle: 50
        minIdle: 0



management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false