#========================秒杀服务 开发环境====================================

server:
  port: 8085
spring:
  application:
    name: toucan-shopping-second-kill #应用名称
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒没发心跳将剔除
    lease-renewal-interval-in-seconds: 1 #心跳1秒
    prefer-ip-address: true
    instance-id: 127.0.0.1:8085    #使用IP地址注册
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


toucan:
  app-code: 10001001 #自定义应用编码
  admin-auth:
    enabled: false
    name: toucan-shopping-admin-auth