#========================定时任务调度 开发环境====================================

server:
  port: 8092
  servlet:
    context-path: /toucan-shopping-scheduler
spring:
  application:
    name: toucan-shopping-web #应用名称
  zipkin: #链路追踪
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
    nacos:
      discovery:
        ip: ${toucan.ip}    #使用IP地址注册
        port: ${server.port}
        register-enabled: false
        server-addr: http://${toucan.nacos.ip}:${toucan.nacos.port}
        metadata:
          preserved.heart.beat.interval: 4000 #心跳间隔。时间单位:秒。心跳间隔
          preserved.heart.beat.timeout: 4500 #心跳暂停。时间单位:秒。 即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.ip.delete.timeout: 4500 #Ip删除超时。时间单位:秒。即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例删除：
#eureka:
#  client:
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #请求时间超过5秒产生熔断
      circuitBreaker:
        requestVolumeThreshold: 8  #10秒内8个以上请求失败,产生熔断




toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #自定义应用编码
  admin-auth:
    enabled: true
    name: toucan-shopping-admin-auth