#========================定时任务调度 开发环境====================================

server:
  port: 8092
  servlet:
    context-path: /toucan-shopping-scheduler
spring:
  application:
    name: toucan-shopping-web #应用名称
  zipkin: #链路追踪
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #请求时间超过5秒产生熔断
      circuitBreaker:
        requestVolumeThreshold: 8  #10秒内8个以上请求失败,产生熔断




toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #自定义应用编码
  user-center:
    enabled: true
    name: toucan-shopping-user-center