cluster.name: elasticsearch
node.name: node-1
node.attr.rack: r1
path.data: /usr/path/to/data
path.logs: /usr/path/to/logs
network.bind_host: 127.0.0.1
network.publish_host: 8.140.187.184
network.host: 127.0.0.1
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]
http.port: 9200
#开启密码验证
xpack.security.enabled: true
xpack.ml.enabled: false
xpack.security.transport.ssl.enabled: true