server:
  port: 8081
spring:
  application:
    name: toucan-shopping-eureka #应用名称
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:8081    #使用IP地址注册
  client:
    registerWithEureka: false #禁止注册自己
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  server:
    useReadOnlyResponseCache: false #关闭readOnlyCacheMap缓存
    enableSelfPreservation: false #关闭保护机制
    evictionIntervalTimerInMs: 2000 #2秒扫描一次失联服务
    renewalPercentThreshold: 0 #单独起一台
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"