#======================== 监控服务 生产环境 ====================================

# mybatis
mybatis.type-aliases-package=com.toucan.shopping.*.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=3000
mybatis.mapperLocations=classpath*:com/toucan/**/mapper/*Mapper.xml

# ShardingSphere 数据源
spring.shardingsphere.datasource.names=ds0
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds0.url=jdbc:mysql://rm-2ze33642t0ju9a897oo.mysql.rds.aliyuncs.com:3306/toucan_shopping_api_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds0.username=toucan_shopping_majian000
spring.shardingsphere.datasource.ds0.password=mj_toucan_shopping_7612
spring.shardingsphere.datasource.ds0.driver-class-name=com.mysql.cj.jdbc.Driver

# 分表 日期分片(天)
spring.shardingsphere.rules.sharding.sharding-algorithms.table-date-day-sharding-algorithms.type=TableDateDayAlgorithm
spring.shardingsphere.rules.sharding.sharding-algorithms.table-date-day-sharding-algorithms.props.instance-name=apiMonitorService

# 主键生成器
spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=101

# api_monitor_record 按天分表
spring.shardingsphere.rules.sharding.tables.api_monitor_record.actual-data-nodes=ds0.api_monitor_record_$->{1..31}
spring.shardingsphere.rules.sharding.tables.api_monitor_record.table-strategy.standard.sharding-column=sharding_date
spring.shardingsphere.rules.sharding.tables.api_monitor_record.table-strategy.standard.sharding-algorithm-name=table-date-day-sharding-algorithms

# api_monitor_metrics 按天分表
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.actual-data-nodes=ds0.api_monitor_metrics_$->{1..31}
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.table-strategy.standard.sharding-column=sharding_date
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.table-strategy.standard.sharding-algorithm-name=table-date-day-sharding-algorithms
