#======================== 监控服务 生产环境 ====================================

server:
  port: ${toucan.port}

spring:
  application:
    name: toucan-shopping-api-monitor
  zipkin:
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
  mvc:
    servlet:
      load-on-startup: 100
  cloud:
    nacos:
      discovery:
        ip: ${toucan.ip}
        port: ${toucan.port}
        server-addr: ${toucan.nacos.ip}:${toucan.nacos.port}
        username: ${toucan.nacos.username}
        password: ${toucan.nacos.password}
        metadata:
          preserved.heart.beat.interval: 4000
          preserved.heart.beat.timeout: 4500
    openfeign:
      circuitbreaker:
        enabled: true


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 8
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  thread-pool-bulkhead:
    configs:
      default:
        max-thread-pool-size: 50
        core-thread-pool-size: 20
        queue-capacity: 500



toucan:
  machine-id: 2201
  app-code: 10001008
  plugins:
    traceId:
      enabled: true
    apiMonitor:
      enabled: true
      scanPackages:
        - com.toucan.shopping
      excludePatterns:
        - /actuator/**
        - /error
  modules:
    log: #日志模块
      param:
        request:
          enabled: false
          content-type-list[0]: application/x-www-form-urlencoded
          content-type-list[1]: application/json
        response:
          enabled: false
          content-type-list[0]: application/json
      email:
        enabled: true
        title: ——监控服务——异常邮件
        ignore-exception-list[0]: javax.mail.MessagingException
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian

management:
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
