#======================== 监控服务 生产环境 ====================================

# mybatis
mybatis.type-aliases-package=com.toucan.shopping.*.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=3000
mybatis.mapperLocations=classpath*:com/toucan/**/mapper/*Mapper.xml

# ShardingSphere 数据源（按年分库）
spring.shardingsphere.datasource.names=ds2026,ds2027
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource

spring.shardingsphere.datasource.ds2026.url=jdbc:mysql://${toucan.mysql.ip}:3306/toucan_shopping_api_monitor_2026?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds2026.username=${toucan.mysql.username}
spring.shardingsphere.datasource.ds2026.password=${toucan.mysql.password}
spring.shardingsphere.datasource.ds2026.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.ds2027.url=jdbc:mysql://${toucan.mysql.ip}:3306/toucan_shopping_api_monitor_2027?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.ds2027.username=${toucan.mysql.username}
spring.shardingsphere.datasource.ds2027.password=${toucan.mysql.password}
spring.shardingsphere.datasource.ds2027.driver-class-name=com.mysql.cj.jdbc.Driver


# 分库 日期分片(年)
spring.shardingsphere.rules.sharding.sharding-algorithms.database-year-sharding-algorithms.type=DBDateYearAlgorithm
spring.shardingsphere.rules.sharding.sharding-algorithms.database-year-sharding-algorithms.props.instance-name=apiMonitorService

# 分表 日期分片(月)
spring.shardingsphere.rules.sharding.sharding-algorithms.table-date-month-sharding-algorithms.type=TableDateMonthAlgorithm
spring.shardingsphere.rules.sharding.sharding-algorithms.table-date-month-sharding-algorithms.props.instance-name=apiMonitorService

# 主键生成器
spring.shardingsphere.rules.sharding.key-generators.snowflake.type=SNOWFLAKE
spring.shardingsphere.rules.sharding.key-generators.snowflake.props.worker-id=101

# 默认分库策略（按年）
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-column=sharding_date
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name=database-year-sharding-algorithms

# api_monitor_record 分表配置
spring.shardingsphere.rules.sharding.tables.api_monitor_record.actual-data-nodes=ds${2026..2027}.api_monitor_record_${2026..2027}_${1..12}
spring.shardingsphere.rules.sharding.tables.api_monitor_record.table-strategy.standard.sharding-column=sharding_date
spring.shardingsphere.rules.sharding.tables.api_monitor_record.table-strategy.standard.sharding-algorithm-name=table-date-month-sharding-algorithms

# api_monitor_metrics 分表配置
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.actual-data-nodes=ds${2026..2027}.api_monitor_metrics_${2026..2027}_${1..12}
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.table-strategy.standard.sharding-column=sharding_date
spring.shardingsphere.rules.sharding.tables.api_monitor_metrics.table-strategy.standard.sharding-algorithm-name=table-date-month-sharding-algorithms
