#========================商城客户端 开发环境====================================

server:
  port: 8083
spring:
  application:
    name: toucan-shopping-web #应用名称
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
    nacos:
      discovery:
        ip: ${toucan.ip}    #使用IP地址注册
        port: ${server.port}
        register-enabled: false
        server-addr: http://${toucan.nacos.ip}:${toucan.nacos.port}
        metadata:
          preserved.heart.beat.interval: 4000 #心跳间隔。时间单位:秒。心跳间隔
          preserved.heart.beat.timeout: 4500 #心跳暂停。时间单位:秒。 即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.ip.delete.timeout: 4500 #Ip删除超时。时间单位:秒。即服务端1.5秒收不到客户端心跳，会将该客户端注册的实例删除：
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    view:
      suffix: .html
    servlet:
      load-on-startup: 100
    static-path-pattern: /static/**
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/
    settings:
      template_exception_handler: com.toucan.shopping.modules.freemarker.exception.PageErrorException
  servlet:
    multipart:
      max-file-size: 5MB  #单个文件最大5MB
      max-request-size: 15MB #单次请求上传文件最大15NB
  compression: #开启gzip压缩
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048 #只压缩2MB以上的内容





#eureka:
#  client:
#    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
hystrix:
  threadpool:
    default:
      coreSize: 80 #最大并发数
      maxQueueSize: 1500 #最大队列长度
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #请求时间超过30秒产生熔断
      circuitBreaker:
        requestVolumeThreshold: 15  #30秒内15个以上请求失败,产生熔断



#开启饥饿加载
ribbon:
  OkToRetryOnAllOperations: true #开启重试机制
  MaxAutoRetriesNextServer: 2 #重试其他实例最大重试次数
  MaxAutoRetries: 1 #同一实例重试次数
  ServerListRefreshInterval: 3000 #3秒钟更新一次服务列表缓存
  eager-load:
    enabled: true
    clients: "toucan-shopping-category,\
              toucan-shopping-order,\
              toucan-shopping-product,\
              toucan-shopping-user,\
              toucan-shopping-area,\
              toucan-shopping-gateway,\
              toucan-shopping-stock"





toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #自定义应用编码
  #雪花算法ID相关
  workerId: 0 #工作ID 0~31, 每个服务实例都有一个工作ID
  datacenterId: 0 #数据中心ID (0~31)
  shopping-pc: #PC端配置
    pc-index-column-type-code: PC_INDEX_SHANGPINTUIJIAN #PC端首页商品推荐栏目编码
    freemarker:
      release-mapping-url: /htmls/release/**
      preview-mapping-url: /htmls/preview/**
      release-location: C:/toucan_shopping_htmls/web/htmls/release/
      preview-location: C:/toucan_shopping_htmls/web/htmls/preview/
      ftl-location: templates/
  shopping-seller-web-pc: #卖家PC端配置
    base-path: http://localhost:8101/
  message-web-pc:
    base-path: http://localhost:8102/
  user:
    head-sculpture-max-size: 2048 #头像最大长度2MB(单位KB)
    default-head-sculpture: group1/M00/00/00/rB5PVWC0wtCAfEp6AAAMz-h0lpc563_big.jpg
  user-auth:
    enabled: true
    name: toucan-shopping-user
    login-salt: 0.4947 #这个必须要修改成你自己的,要不然会有很严重的安全性问题
    #HTTP权限请求头
    # 例如 商城C端 Cookie:uid=d10590b318544049ba2104d1f5517a7d;lt=d10590b318544049ba2104d1f5517a7d
    http-toucan-auth-header: Cookie
    #当前项目登录页
    login-page: /page/user/login
    #没有权限时跳转页面
    page-403: /403
    #拦截指定路径
    path-patterns: /**
    #忽略拦截
    exclude-path-patterns: /**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.gif,/**/*.json,/**/*.ico
    #共享会话的所有域名
    sso-set-cookie-url-list: "http://127.0.0.1:8083/api/sso/setCookie,\
                              http://localhost:8083/api/sso/setCookie,\
                              http://127.0.0.1:8101/api/sso/setCookie,\
                              http://localhost:8101/api/sso/setCookie,\
                              http://127.0.0.1:8102/api/sso/setCookie,\
                              http://localhost:8102/api/sso/setCookie"
  plugins:
    xss-filter:
      enabled: true
      exclude-paths:  #排除路径,多个用,分割(不支持正则,只有绝对路径,例如/user/login/password/form,/login/password)
  modules:
    email: #邮件模块
      enabled: true
      protocol: smtp
      smtp: #smtp服务器配置
        host: smtp.163.com #SMTP服务器
        auth: true #SMTP认证
        port: 465
        socketFactory-class: javax.net.ssl.SSLSocketFactory
        socketFactory-fallback: false
      sender: mmdrss@163.com #发件人
      sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
    log: #日志模块
      email:
        enabled: false
        title: ——商城PC端——异常邮件
        ignore-exception-list[0]: javax.mail.MessagingException
        ignore-exception-list[1]: com.toucan.shopping.modules.exception.user.UserHeaderException
        protocol: smtp
        smtp: #smtp服务器配置
          host: smtp.163.com #SMTP服务器
          auth: true #SMTP认证
          port: 465
          socketFactory-class: javax.net.ssl.SSLSocketFactory
          socketFactory-fallback: false
        sender: mmdrss@163.com #发件人
        sender-authentication-code: IJHWJFZINFUPQIUC #发件人授权码
        receiver-list[0]:
          email: 695391446@qq.com
          name: majian
    toucanRedis: #redis模块
      select: single # 可选值 single:单实例 cluster:集群
      timeout: 10000
      password: mj_tocan_redis_7612 #多个集群要求每个密码统一
      #单实例
      host: 8.140.187.184
      port: 6379
      database: 0
      #集群配置
      hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
      maxRedirects: 3 #最大连接转移数
      #jedis pool配置
      maxActive: 50 #最大活跃数
      maxWaitMillis: 15 #最大等待数
      maxIdle: 50 #最大核心线程数
      minIdle: 0 #最小核心线程数
    contentCache:
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    areaCache:
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    categoryCache:
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    skylarkLock: #云雀分布式锁
      type: redis #中间件类型
      redis:
        select: single # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: mj_tocan_redis_7612 #多个集群要求每个密码统一
        #单实例
        host: 8.140.187.184
        port: 6379
        database: 0
        #集群配置
        hosts: 192.168.80.129:6380,192.168.80.129:6381,192.168.80.129:6382 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
