#========================商城客户端 开发环境====================================

server:
  port: 8083
spring:
  application:
    name: toucan-shopping-web #应用名称
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
  zipkin: #链路追踪
    enabled: false
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
  mvc: #启动初始化servletdispatcher
    servlet:
      load-on-startup: 100
    static-path-pattern: /static/**
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/



eureka:
  client:
    registryFetchIntervalSeconds: 3 #3秒更新本地服务列表
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #请求时间超过5秒产生熔断
      circuitBreaker:
        requestVolumeThreshold: 8  #10秒内8个以上请求失败,产生熔断



#开启饥饿加载
ribbon:
  OkToRetryOnAllOperations: true #开启重试机制
  MaxAutoRetriesNextServer: 2 #重试其他实例最大重试次数
  MaxAutoRetries: 1 #同一实例重试次数
  ServerListRefreshInterval: 3000 #3秒钟更新一次服务列表缓存
  eager-load:
    enabled: true
    clients: "toucan-shopping-category,\
              toucan-shopping-order,\
              toucan-shopping-product,\
              toucan-shopping-user,\
              toucan-shopping-gateway,\
              toucan-shopping-stock"





toucan:
  machine-id: 2201 #机器编码
  app-code: 10001001 #自定义应用编码
  admin-auth:
    enabled: true
    name: toucan-shopping-user
    #HTTP权限请求头
    # 例如 后台管理端 Cookie:adminId=d10590b318544049ba2104d1f5517a7d;loginToken=d10590b318544049ba2104d1f5517a7d
    # 例如 商城C端 Cookie:uid=d10590b318544049ba2104d1f5517a7d;lt=d10590b318544049ba2104d1f5517a7d
    http-toucan-auth-header: toucan-auth-header
    #当前项目登录页
    login-page: /page/user/login
    #拦截指定路径
    path-patterns: /**
    #忽略拦截
    exclude-path-patterns: /**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.gif,/**/*.json,/error,/**/*.ico
  modules:
    areaCache:
      redis:
        select: cluster # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: #多个集群要求每个密码统一
        #单实例
        host: 127.0.0.1
        port: 6379
        database: 0
        #集群配置
        hosts: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数
    categoryCache:
      redis:
        select: cluster # 可选值 single:单实例 cluster:集群
        timeout: 10000
        password: #多个集群要求每个密码统一
        #单实例
        host: 127.0.0.1
        port: 6379
        database: 0
        #集群配置
        hosts: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381 #多个用,分割
        maxRedirects: 3 #最大连接转移数
        #jedis pool配置
        maxActive: 50 #最大活跃数
        maxWaitMillis: 15 #最大等待数
        maxIdle: 50 #最大核心线程数
        minIdle: 0 #最小核心线程数