<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.toucan.shopping</groupId>
        <artifactId>toucan-shopping-cloud</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../../../pom.xml</relativePath>
    </parent>

    <groupId>com.toucan.shopping.cloud.modules.apps.config</groupId>
    <artifactId>toucan-shopping-message-web-single-config</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <description>消息中心web端单服务配置启动类</description>

    <dependencies>
        <!-- Redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
        </dependency>

        <!-- Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Common modules -->
        <dependency>
            <groupId>com.toucan.shopping.modules.common</groupId>
            <artifactId>toucan-shopping-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.toucan.shopping.modules.common</groupId>
            <artifactId>toucan-shopping-common-persistence</artifactId>
        </dependency>

        <!-- XSS Starter -->
        <dependency>
            <groupId>com.toucan.shopping.cloud.starter</groupId>
            <artifactId>toucan-shopping-xss-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
