spring.main.allow-bean-definition-overriding=true
toucan.app-code=10001001
toucan.ip=127.0.0.1
toucan.machine-id=1

# DataSource
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/toucan_shopping_admin_auth?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# MyBatis
mybatis.mapper-locations=classpath*:com/toucan/**/mapper/*Mapper.xml
mybatis.type-aliases-package=com.toucan.shopping.*.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Redis
toucan.modules.skylarkLock.type=redis
toucan.modules.skylarkLock.redis.select=single
toucan.modules.skylarkLock.redis.timeout=10000
toucan.modules.skylarkLock.redis.host=127.0.0.1
toucan.modules.skylarkLock.redis.port=6379
toucan.modules.skylarkLock.redis.database=0
toucan.modules.skylarkLock.redis.maxActive=50
toucan.modules.skylarkLock.redis.maxWaitMillis=15
toucan.modules.skylarkLock.redis.maxIdle=50
toucan.modules.skylarkLock.redis.minIdle=0
