#========================应用中心 开发环境====================================

server:
  port: 8091
spring:
  application:
    name: toucan-shopping-app-center #应用名称
  zipkin: #链路追踪
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:8091    #使用IP地址注册
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
