#========================用户中心界面 开发环境====================================

server:
  port: 8088
  servlet:
    context-path: /toucan-shopping-user-center-web
spring:
  application:
    name: toucan-shopping-user-center-web #应用名称
  zipkin: #链路追踪
    enabled: true
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率 1全部采集
        probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

toucan:
  app-code: 10000001 #自定义应用编码
  user-center:
    enabled: true
    name: toucan-shopping-user-center
    #HTTP权限请求头
    # 例如 后台管理端 Cookie:adminId=d10590b318544049ba2104d1f5517a7d;loginToken=d10590b318544049ba2104d1f5517a7d
    # 例如 商城C端 Cookie:userId=d10590b318544049ba2104d1f5517a7d;loginToken=d10590b318544049ba2104d1f5517a7d
    http-bbs-auth-header: Cookie
    #当前项目登录页
    login-page: /login/page
    #拦截指定路径
    path-patterns: /**
    #忽略拦截
    exclude-path-patterns: /**/*.js,/**/*.css,/**/*.jpg,/**/*.png,/**/*.gif,/**/*.json
